### ISSUE TITLE
Preselect first grafana datasource or allow setting a default

### ISSUE THREAD

**Issue by kbudde** [promlabs/promlens-public#16]
At the moment I always have to select "prometheus" from list of grafana datasources.
It would be nice to use it by default or add an option to configure the default.

**Comment by juliusv** [comment]
Hi @kbudde, right now PromLens preselects the datasource that is marked as the default datasource in Grafana (a boolean toggle in the Grafana datasource options). But I guess you'd like to not set the default in Grafana, but separately in PromLens?

Also, just to make sure that things are working correctly: you are not seeing any datasources in PromLens that are not Prometheus datasources, right? (that would be a bug)

**Comment by juliusv** [comment]
Btw., there is also already a `--web.default-prometheus-url=<url>` command-line flag. However, that one only works for the non-Grafana manually entered server URL. I could also add another flag `--web.default-datasource-id=<id>` that could be used to override the default Grafana datasource ID when using the Grafana integration.

**Comment by juliusv** [comment]
I ended up adding a `--grafana.default-datasource-id=<id>` command-line flag that allows overriding Grafana's default datasource ID. You can already trying out by using the Docker image version `promlabs/promlens:v1.0.0-override-ds-id`. It will also be in the next release (which may take a while though).

To find the ID of a Grafana datasource, edit the datasource in Grafana and you will see the ID in the URL, e.g. `http://localhost:3000/datasources/edit/<datasource-id>/`.

Let me know if that solves your problem!

**Comment by kbudde** [comment]
Hi @juliusv ,
thank you for your support.
For my issue it was already enough to define the prometheus datasource as default.

**Comment by juliusv** [comment]
@MacroPower Great! And just curious, I guess you were not able to change the default in Grafana directly for some other reasons (e.g. because it was a default needed for other scenarios)?

**Comment by MacroPower** [comment]
@juliusv The default we use is random walk. There are just a lot of datasources in Grafana, with a lot of very unique users and use-cases, so setting Prometheus as a default specifically for PromLens (or the relatively small Prometheus userbase) wouldn't be ideal.

**Comment by juliusv** [comment]
That makes a lot of sense, thanks for clarifying!

Will close this issue then, although it's not fully released yet, it's implemented.

**Comment by juliusv** [comment]
(whoops, it was already closed)
