### ISSUE TITLE
Allow excluding range when selecting expressions

### ISSUE THREAD

**Issue by MacroPower** [promlabs/promlens-public#17]
One of the great features of PromLens is being able to click on individual expressions to see their results. So even though my whole query returns 1 series, I can click "up" to see all 75 that were aggregated in max().

![image](https://user-images.githubusercontent.com/5648814/120375839-3b1f2f00-c2e9-11eb-8acf-ff92d79e8daa.png)

However, this can break when using a range.

![image](https://user-images.githubusercontent.com/5648814/120375556-f0051c00-c2e8-11eb-8839-9322e8865192.png)

In this case if I select the `up` sub-expression, it runs `up[15m]` which obviously can't be graphed:

![image](https://user-images.githubusercontent.com/5648814/120375754-26db3200-c2e9-11eb-95fa-9fd5f183eefe.png)

Technically you could see something by moving over to table, but this is kind of inconvenient and sometimes I would just like to see the results of `up`. So, my suggestion is to allow users to select either `up` or `up[15m]`. For example, clicking `up` would query `up` but clicking `[15m]` would query `up[15m]`. It may also be helpful to include a hint for users who try to graph `up[15m]`, e.g. "This looks like a range vector, click here to query the instant vector", similar to how you currently try to help out users who rate over a gauge by suggesting deriv().

**Comment by juliusv** [comment]
@MacroPower Hah, I've been thinking something similar, although I do want to keep the rule that each node/subexpression has only one clickable area. How about the following though: when clicking on a range vector selector and having the Graph tab open, it could just graph the instant vector selector, but with a big warning above the graph: "Can't graph range vector selectors, graphing the equivalent instant vector selector instead."?

**Comment by MacroPower** [comment]
@juliusv I think that would work too, as I can't think of a case where seeing instant over range as a table would really matter.

**Comment by juliusv** [comment]
Yeah, the table view would remain unchanged, as it can display range vectors.

But I implemented my idea now for graphs:

![graphing-range-selectors](https://user-images.githubusercontent.com/538008/120381626-ff08c000-c322-11eb-8875-09266c4710b4.png)

Will be in the next release, thanks for the idea :)

**Comment by juliusv** [comment]
Just released PromLens v1.1.0, which includes the above-mentioned behavior.
