### ISSUE TITLE
Allow to run Promlens without root user

### ISSUE THREAD

**Issue by weyert** [promlabs/promlens-public#22]
I was informed about the pod security policy that Promlens official docker image is running under the root user. I am wondering if it would be possible to change this?

**Comment by juliusv** [comment]
That's a good point, thanks! I'll switch that to user `nobody` in the next few weeks.

In the meantime, if you want to create a custom non-root-user Docker image, you could copy over the binary (at `/promlens`) from the PromLabs image into a blank `alpine:3` image (and maybe run `apk add --no-cache ca-certificates` to get certs in there).

**Comment by juliusv** [comment]
Hi! There's great news today: PromLens is now fully open-source and has been migrated to the Prometheus project: https://twitter.com/juliusvolz/status/1584897156405940224

As part of that open-sourcing, this existing repository will no longer be used for tracking issues or creating any updates. Please feel free to open issues against the new repo as well, or perhaps even contribute changes (now that it's OSS!) :)

In the new location and release process, the Docker images are no longer running as root, so this issue should be solved :)
