### ISSUE TITLE
UI shows old data instead of new.

### ISSUE THREAD

**Issue by McMerph** [promlabs/promlens-public#23]
To reproduce just execute `timestamp(up)` query, wait a little, and re-execute query (hit `Enter` in query input)

![image](https://user-images.githubusercontent.com/29835709/158558024-1482cba0-f7c1-4e0a-bd61-e1664e462acd.png)

**Comment by juliusv** [comment]
@McMerph Good point, thanks! Yes, pressing return currently only triggers a re-evaluation of the table/graph data if either the expression or the explicit time inputs change. I realize that's surprising and not what you'd want. Will see how I can trigger a complete re-evaluation in that case!

**Comment by altokarev** [comment]
hey, @juliusv 👋 

are there any updates on this issue?

**Comment by juliusv** [comment]
@altokarev Thanks for the ping, it's indeed high time for another PromLens release to include some of the requested issues. I just managed to implement retriggering the query upon pressing Enter. I hope that I can implement a few more of the feature requests and then do a release in the next couple of weeks.

**Comment by juliusv** [comment]
@altokarev Plans have changed a bit - There might be even better news than another PromLens release in the near future. Stay tuned :)

**Comment by altokarev** [comment]
> @altokarev Plans have changed a bit - There might be even better news than another PromLens release in the near future. Stay tuned :)

whoa! 🎉

**Comment by juliusv** [comment]
Hi! There's great news today: PromLens is now fully open-source and has been migrated to the Prometheus project: https://twitter.com/juliusvolz/status/1584897156405940224

As part of that open-sourcing, this existing repository will no longer be used for tracking issues or creating any updates. Please feel free to open issues against the new repo as well, or perhaps even contribute changes (now that it's OSS!) :)

This issue should be solved by the first open-source release, so closing this issue.
