### ISSUE TITLE
Add support for MetricsQL

### ISSUE THREAD

**Issue by freeseacher** [promlabs/promlens-public#25]
Promlens gave a great visibility for cardinality of metrics, but what about support of metricsql from victroriametrics. Now just PromQL queries work, would you be so kind to add support for https://docs.victoriametrics.com/MetricsQL.html
As far as i know guys also ship it as a separate library https://github.com/VictoriaMetrics/metricsql

**Comment by juliusv** [comment]
Hi, indeed PromLens aims to support all PromQL-compatible systems, but we do not plan on implementing support for single-vendor non-PromQL-compatible languages like MetricsQL. When you choose MetricsQL, be aware that you will be a bit "stuck" in the VictoriaMetrics ecosystem and will encounter compatibility issues like that with other common Prometheus tooling as well (promtool, PromQL query proxies, etc.), as those tools stick to the upstream language standard. I wrote a few blog posts about compatibility testing calling out this issue, which you can find along with compatibility data here: https://promlabs.com/promql-compliance-tests/

**Comment by juliusv** [comment]
Closing this as per the comment above.

**Comment by freeseacher** [comment]
Yep. tnx for reply. looks like i've missed it somehow. 

For me that is just matter of which vendor lock i've got. Recently guys updated their vmui and added pretty simple and powerful interface for cardinality debug and tracing of metricsql queries. 

that solves 100% of my needs.

**Comment by juliusv** [comment]
Well, with Prometheus there is no single vendor, but it's totally fine to go with something else like VM of course. Glad it solves your issue :)
