### ISSUE TITLE
Error validating server health: Failed to fetch

### ISSUE THREAD

**Issue by vikaskoppineedi** [promlabs/promlens-public#26]
Confused, very confused on how to run promlens. 

I am trying to run promlens in my test cluster where I am running the prometheus server in a pod, with a service. 

I have a troubelshooting pod within the same cluster and tried to see if I am able to reach prometheus url. 

these are the URLs that i tried and they worked from the troubleshooting pod. 

curl http://prometheus-prometheus.monitoring.svc.cluster.local:9090

using cluster ip http://172.20.2.9:9090

what ever url i tried, all of them say Failed to fetch.

Can anybody help ?

**Comment by juliusv** [comment]
Hi @vikaskoppineedi, without a license key (and thus Grafana backend proxying disabled), PromLens can only send queries to Prometheus directly from the browser it is running in (see https://github.com/promlabs/promlens-public#preview-features). So your browser would need to be able to reach the Prometheus server as well, which may require extra steps with Kubernetes - can you confirm that opening the Prometheus server URL in your browser works?

**Comment by vikaskoppineedi** [comment]
@juliusv I got it resolved. It clicked after you mentioned that the browser should be able to reach. So i just turned on the VPN and it works. !

**Comment by juliusv** [comment]
Great!
